### ISSUE TITLE
Typo fix needed

### ISSUE THREAD

**Issue by fmedinac** [front-end-carioca/fec-2016#10]
SOBRE
O Front-end Carioca Surgiu de uma idéia dentro da comunidade de desenvolvedores web, tendo como `obijetivo` enriquecer o conhecimento profissional através de ciclos de palestras, workshops, networking e é claro bastante incentivo.

**Comment by gbrlsepulveda** [comment]
Valeu @fmedinac temos um pull request pendente com essa correção #9

**Comment by gbrlsepulveda** [comment]
Valeu @fmedinac. Foi feito um PR resolvendo essa questão #7 mas ainda não foi deployado.

cc @front-end-carioca/member
