### ISSUE TITLE
Update speakers

### ISSUE THREAD

**Issue by pedropolisenso** [front-end-carioca/fec-2016#13]
Precisamos atualizar a foto do Asael da Toptal pela foto do Igor que é também da Toptal, mas é daqui do RJ e alterar as informações dele. Segue abaixo a descrição completa.

**Título:** REST-fuuuu 
**Descrição:** Conheça o conceito RESTful e boas práticas para criação e consumo de APIs. 
**Foto:** https://assets.toptal.io/uploads/user/photo/13047/large_ef2861535f11b186c3a6a64ce892b9ab.JPG 
**Cargo:** Desenvolvedor PHP/React Freelancer na Toptal 
**Mini-bio:** Trabalha com desenvolvimento web há mais de 8 anos, sendo pelo menos 4 destes com aplicações JS e sistemas REST. Atualmente é freelancer remoto para empresas estrangeiras na Toptal. Dedica tempo livre a projetos open-source, pet projects e ao grupo de desenvolvedores PHP local, o PHPRio. 
**Github:** github.com/igorsantos07

**Comment by gbrlsepulveda** [comment]
Vou preparar um PR, envio ainda hoje.

**Comment by pedropolisenso** [comment]
@gbrlsepulveda você já preparou esse aqui?

**Comment by pedropolisenso** [comment]
@gbrlsepulveda acabei de fechar essa issue.
